project_id = "shfnpzfqtrfzdklnhatf"

[functions.send-newsletter]
verify_jwt = true

[functions.create-post]
verify_jwt = false

[functions.generate-post]
verify_jwt = true

[functions.analyze-seo]
verify_jwt = true

[functions.ping-search-engines]
verify_jwt = true